#!/usr/bin/env python3
"""LLM-assisted: Claude Code (claude-sonnet-4-6), 2026-06-26
Generate BUG_COVERAGE.md from issue metadata.yaml files.

Usage:
    python3 tools/generate_bug_coverage.py [--output BUG_COVERAGE.md]

Reads all issues/*/metadata.yaml and produces a summary table.
Exit code: 0 on success.
"""

import sys, os, glob, json
from datetime import datetime

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required. pip install pyyaml", file=sys.stderr)
    sys.exit(2)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

COVERAGE_LEVELS = {
    0: "Concept only",
    1: "Reproduced",
    2: "Candidate implemented",
    3: "Regression-tested",
    4: "Benchmarked",
    5: "Fully validated",
}

def infer_level(data):
    """Infer coverage level from status fields."""
    apply_ok = data.get("apply_status") == "passed"
    test_ok  = data.get("test_status") == "passed"
    bench_ok = data.get("benchmark_status") == "passed"
    build_ok = data.get("build_status") == "passed"
    has_repro = os.path.isfile(
        os.path.join(REPO_ROOT, "issues", data.get("id",""), "reproduce.sh")
    )

    if bench_ok:  return 4
    if test_ok:   return 3
    if apply_ok:  return 2
    if has_repro: return 1
    return 0


def load_issues():
    issues = []
    for path in sorted(glob.glob(os.path.join(REPO_ROOT, "issues/*/metadata.yaml"))):
        with open(path) as f:
            data = yaml.safe_load(f)
        data["_level"] = infer_level(data)
        issues.append(data)
    return issues


def generate(issues, output_path):
    now = datetime.utcnow().strftime("%Y-%m-%d")
    lines = [
        "# Bug Coverage Report",
        f"<!-- Auto-generated by tools/generate_bug_coverage.py on {now} -->",
        f"<!-- LLM-assisted: Claude Code (claude-sonnet-4-6), 2026-06-26 -->",
        "",
        "This document reports the verified bug and performance-pathology coverage",
        "for the Emacs Performance Patch Atlas. Coverage levels are defined in",
        "[docs/coverage-claims.md](docs/coverage-claims.md).",
        "",
        "---",
        "",
        "## Coverage Table",
        "",
        "| ID | Title | Classification | Platform | Apply | Test | Bench | Level |",
        "|---|---|---|---|---|---|---|---|",
    ]

    level_counts = {i: 0 for i in range(6)}
    for d in issues:
        ident = d.get("id", "?")
        title = d.get("title", "?")
        if len(title) > 55:
            title = title[:52] + "..."
        cls   = d.get("classification", "?")
        plat  = ", ".join(d.get("platforms", ["?"]))
        apply = d.get("apply_status", "?")
        test  = d.get("test_status", "?")
        bench = d.get("benchmark_status", "?")
        level = d["_level"]
        level_counts[level] += 1
        lines.append(
            f"| {ident} | {title} | {cls} | {plat} "
            f"| {apply} | {test} | {bench} | {level} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Level Summary",
        "",
        "| Level | Definition | Count |",
        "|---|---|---|",
    ]
    for lvl, name in COVERAGE_LEVELS.items():
        lines.append(f"| {lvl} | {name} | {level_counts[lvl]} |")

    lines += [
        "",
        "---",
        "",
        "## Minimum Target Status",
        "",
    ]
    at_level1_plus = sum(v for l, v in level_counts.items() if l >= 1)
    at_level3_plus = sum(v for l, v in level_counts.items() if l >= 3)
    at_level4_plus = sum(v for l, v in level_counts.items() if l >= 4)
    apply_passed = sum(1 for d in issues if d.get("apply_status")=="passed")
    test_passed  = sum(1 for d in issues if d.get("test_status")=="passed")
    bench_passed = sum(1 for d in issues if d.get("benchmark_status")=="passed")

    def check(val, required, label):
        status = "PASS" if val >= required else "FAIL"
        return f"| {label} | {required} | {val} | {status} |"

    lines += [
        "| Requirement | Required | Actual | Status |",
        "|---|---|---|---|",
        check(at_level1_plus, 5, "Issues at Level 1+"),
        check(apply_passed,   5, "Patches that apply (git apply --check passed)"),
        check(test_passed,    5, "Tests passed"),
        check(bench_passed,   2, "Benchmarks passed"),
        check(at_level3_plus, 3, "Issues at Level 3+"),
        check(at_level4_plus, 2, "Issues at Level 4+"),
        "",
        "---",
        "",
        "## Issue Summaries",
        "",
    ]

    for d in issues:
        ident = d.get("id","?")
        title = d.get("title","?")
        level = d["_level"]
        plats = ", ".join(d.get("platforms",[]))
        limits = d.get("known_limitations", [])
        lines += [
            f"### {ident}: {title}",
            "",
            f"- **Level:** {level} ({COVERAGE_LEVELS[level]})",
            f"- **Classification:** {d.get('classification','?')}",
            f"- **Platforms:** {plats}",
            f"- **Affected revision:** `{d.get('affected_revision','?')}`",
            f"- **Candidate fix:** `{d.get('candidate_fixes',{}).get('primary','?')}`",
            f"- **Apply:** {d.get('apply_status','?')}",
            f"- **Build:** {d.get('build_status','?')}",
            f"- **Test:** {d.get('test_status','?')}",
            f"- **Benchmark:** {d.get('benchmark_status','?')}",
        ]
        if limits:
            lines.append("- **Known limitations:**")
            for lim in limits[:3]:
                lines.append(f"  - {lim}")
        lines.append("")

    lines += [
        "---",
        "",
        f"*Generated: {now}. All content LLM-assisted (Claude Code, claude-sonnet-4-6).*",
    ]

    content = "\n".join(lines) + "\n"
    with open(output_path, "w") as f:
        f.write(content)
    print(f"Written: {output_path}")
    return 0


def main():
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=os.path.join(REPO_ROOT, "BUG_COVERAGE.md"))
    args = parser.parse_args()

    issues = load_issues()
    if not issues:
        print("No issues found.", file=sys.stderr)
        return 1
    return generate(issues, args.output)


if __name__ == "__main__":
    sys.exit(main())
